version: '3'
services:
  nginx:
    depends_on:
      - api
      - frontend
    restart: always
    build: 
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - 3050:80
  api:
    image: anatholyb/gecko_api:latest
  frontend:
    stdin_open: true
    image: anatholyb/gecko_cabane_restaurant:latest

